"""create document table

Revision ID: 7913ae7db144
Revises: 
Create Date: 2026-07-24 01:53:16.456445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7913ae7db144'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('document_group_id', sa.Uuid(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.Enum('CONTRACT', 'VMF', 'PURCHASE_ORDER', 'INVOICE', 'PAYMENT', name='department_enum'), nullable=False),
    sa.Column('source_system', sa.Enum('SAP', 'ORACLE', 'TALLY', name='source_system_enum'), nullable=False),
    sa.Column('source_document_key', sa.String(length=100), nullable=False),
    sa.Column('business_process', sa.Enum('SUPPLIER', 'INVOICE', 'PURCHASEORDER', 'PAYMENT', name='business_process_enum'), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('document_status', sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='document_status_enum'), nullable=False),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.Enum('PDF', name='mime_type_enum'), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=False),
    sa.CheckConstraint('char_length(file_hash) = 64', name='ck_documents_hash_length'),
    sa.CheckConstraint('document_version >= 1', name='ck_documents_version_positive'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('document_group_id', 'document_version', name='uq_documents_group_version'),
    sa.UniqueConstraint('source_system', 'business_process', 'file_hash', name='uq_documents_source_process_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
