"""create document table

Revision ID: ea331f5351ef
Revises: f56a2e1c0b01
Create Date: 2026-07-28 04:02:28.802922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea331f5351ef'
down_revision: Union[str, Sequence[str], None] = 'f56a2e1c0b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'source_document_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('PROCUREMENT_POLICY', 'CONTRACTING_POLICY', 'SUPPLIER_ONBOARDING_POLICY', 'SINGLE_PAYMENT_REQUEST_POLICY', 'INVOICE_POLICY', 'PAYMENT_POLICY', 'PURCHASING_POLICY', 'SUPPLIER_ONBOARDING_SOP', 'SINGLE_PAYMENT_REQUEST_SOP', 'INVOICE_APPROVAL_SOP', 'PAYMENT_SOP', 'PURCHASE_ORDER_SOP', name='source_document_key_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'source_document_key',
               existing_type=sa.Enum('PROCUREMENT_POLICY', 'CONTRACTING_POLICY', 'SUPPLIER_ONBOARDING_POLICY', 'SINGLE_PAYMENT_REQUEST_POLICY', 'INVOICE_POLICY', 'PAYMENT_POLICY', 'PURCHASING_POLICY', 'SUPPLIER_ONBOARDING_SOP', 'SINGLE_PAYMENT_REQUEST_SOP', 'INVOICE_APPROVAL_SOP', 'PAYMENT_SOP', 'PURCHASE_ORDER_SOP', name='source_document_key_enum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
